require("config.set")
require("config.remap")
require("config.color")

require("plugins.packer")
require("plugins.treesitter")
require("plugins.coc")
require("plugins.fzf")
require("plugins.toggleterm")
require("plugins.nvimtree")
require("plugins.indentblankline")
require("plugins.telescope")
require("plugins.vimtest")
require("plugins.floaterm")
require("plugins.markdownpreview")
